./sig.c: In function 'termsig_handler':
./sig.c:542:7: warning: possible asynchronous-unsafe function ‘termsig_handler‘ in signal handler ‘termsig_sighandler‘ [-fplugin=csigsafe]
       termsig_handler (sig);
       ^~~~~~~~~~~~~~~~~~~~~
./sig.c:573:24: note: function ‘termsig_handler‘ calls function ‘signal_is_trapped‘
   if (sig == SIGINT && signal_is_trapped (SIGINT))
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
./sig.c:573:24: note: function ‘signal_is_trapped‘ is not known to be async-signal-safe
./sig.c:574:5: note: function ‘termsig_handler‘ calls function ‘run_interrupt_trap‘
     run_interrupt_trap (0);
     ^~~~~~~~~~~~~~~~~~~~~~
./sig.c:574:5: note: function ‘run_interrupt_trap‘ is not known to be async-signal-safe
./sig.c:586:5: note: function ‘termsig_handler‘ calls function ‘read_tty_cleanup‘
     read_tty_cleanup ();
     ^~~~~~~~~~~~~~~~~~~
./sig.c:586:5: note: function ‘read_tty_cleanup‘ is not known to be async-signal-safe
./sig.c:590:5: note: function ‘termsig_handler‘ calls function ‘hangup_all_jobs‘
     hangup_all_jobs ();
     ^~~~~~~~~~~~~~~~~~
./sig.c:590:5: note: function ‘hangup_all_jobs‘ is not known to be async-signal-safe
./sig.c:591:3: note: function ‘termsig_handler‘ calls function ‘end_job_control‘
   end_job_control ();
   ^~~~~~~~~~~~~~~~~~
./sig.c:591:3: note: function ‘end_job_control‘ is not known to be async-signal-safe
./sig.c:595:3: note: function ‘termsig_handler‘ calls function ‘unlink_fifo_list‘
   unlink_fifo_list ();
   ^~~~~~~~~~~~~~~~~~~
./sig.c:595:3: note: function ‘unlink_fifo_list‘ is not known to be async-signal-safe
./sig.c:602:3: note: function ‘termsig_handler‘ calls function ‘run_exit_trap‘
   run_exit_trap (); /* XXX - run exit trap possibly in signal context? */
   ^~~~~~~~~~~~~~~~
./sig.c:602:3: note: function ‘run_exit_trap‘ is not known to be async-signal-safe
./sig.c: In function 'set_signal_handler':
./sig.c:635:7: warning: possible asynchronous-unsafe function ‘throw_to_top_level‘ in signal handler ‘sigint_sighandler‘ [-fplugin=csigsafe]
       throw_to_top_level ();
       ^~~~~~~~~~~~~~~~~~~~~
./sig.c:425:7: note: function ‘throw_to_top_level‘ calls function ‘signal_is_trapped‘
   if (signal_is_trapped (SIGINT))
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
./sig.c:425:7: note: function ‘signal_is_trapped‘ is not known to be async-signal-safe
./sig.c:426:5: note: function ‘throw_to_top_level‘ calls function ‘run_interrupt_trap‘
     run_interrupt_trap (1);
     ^~~~~~~~~~~~~~~~~~~~~~
./sig.c:426:5: note: function ‘run_interrupt_trap‘ is not known to be async-signal-safe
./sig.c:430:5: note: function ‘throw_to_top_level‘ calls function ‘parse_and_execute_cleanup‘
     parse_and_execute_cleanup ();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./sig.c:430:5: note: function ‘parse_and_execute_cleanup‘ is not known to be async-signal-safe
./sig.c:433:5: note: function ‘throw_to_top_level‘ calls function ‘run_trap_cleanup‘
     run_trap_cleanup (running_trap - 1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./sig.c:433:5: note: function ‘run_trap_cleanup‘ is not known to be async-signal-safe
./sig.c:436:3: note: function ‘throw_to_top_level‘ calls function ‘give_terminal_to‘
   give_terminal_to (shell_pgrp, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./sig.c:436:3: note: function ‘give_terminal_to‘ is not known to be async-signal-safe
./sig.c:445:3: note: function ‘throw_to_top_level‘ calls function ‘reset_parser‘
   reset_parser ();
   ^~~~~~~~~~~~~~~
./sig.c:445:3: note: function ‘reset_parser‘ is not known to be async-signal-safe
./sig.c:453:3: note: function ‘throw_to_top_level‘ calls function ‘unlink_fifo_list‘
   unlink_fifo_list ();
   ^~~~~~~~~~~~~~~~~~~
./sig.c:453:3: note: function ‘unlink_fifo_list‘ is not known to be async-signal-safe
./sig.c:456:3: note: function ‘throw_to_top_level‘ calls function ‘run_unwind_protects‘
   run_unwind_protects ();
   ^~~~~~~~~~~~~~~~~~~~~~
./sig.c:456:3: note: function ‘run_unwind_protects‘ is not known to be async-signal-safe
./sig.c:462:7: note: function ‘throw_to_top_level‘ calls function ‘fflush‘
       fflush (stdout);
       ^~~~~~~~~~~~~~~
./sig.c:462:7: note: function ‘fflush‘ is not known to be async-signal-safe
./sig.c:463:7: note: function ‘throw_to_top_level‘ calls function ‘__builtin_fputc‘
       fprintf (stderr, "\n");
       ^~~~~~~~~~~~~~~~~~~~~~
./sig.c:463:7: note: function ‘__builtin_fputc‘ is not known to be async-signal-safe
./sig.c:464:7: note: function ‘throw_to_top_level‘ calls function ‘fflush‘
       fflush (stderr);
       ^~~~~~~~~~~~~~~
./sig.c:464:7: note: function ‘fflush‘ is not known to be async-signal-safe
./sig.c:469:25: note: function ‘throw_to_top_level‘ calls function ‘signal_is_trapped‘
       (print_newline && signal_is_trapped (SIGINT)))
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
./sig.c:469:25: note: function ‘signal_is_trapped‘ is not known to be async-signal-safe
