In file included from ./sigbus.c:8:
./sigbus.c: In function 'sigbus_install':
./macro.h:26:24: warning: possible asynchronous-unsafe function ‘__builtin_expect‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                       ~^~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:282:21: note: in expansion of macro '_unlikely_'
                 if (_unlikely_(!(expr)))                                \
                     ^~~~~~~~~~
./macro.h:299:22: note: in expansion of macro 'assert_message_se'
 #define assert(expr) assert_message_se(expr, #expr)
                      ^~~~~~~~~~~~~~~~~
./sigbus.c:88:9: note: in expansion of macro 'assert'
         assert(sn == SIGBUS);
         ^~~~~~
./macro.h:26:24: note: function ‘__builtin_expect‘ is not known to be async-signal-safe
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                       ~^~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:282:21: note: in expansion of macro '_unlikely_'
                 if (_unlikely_(!(expr)))                                \
                     ^~~~~~~~~~
./macro.h:299:22: note: in expansion of macro 'assert_message_se'
 #define assert(expr) assert_message_se(expr, #expr)
                      ^~~~~~~~~~~~~~~~~
./sigbus.c:88:9: note: in expansion of macro 'assert'
         assert(sn == SIGBUS);
         ^~~~~~
In file included from ./macro.h:458,
                 from ./sigbus.c:8:
./log.h:177:9: warning: possible asynchronous-unsafe function ‘log_assert_failed_realm‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
         log_assert_failed_realm(LOG_REALM, (text), __VA_ARGS__)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:283:25: note: in expansion of macro 'log_assert_failed'
                         log_assert_failed(message, __FILE__, __LINE__, __PRETTY_FUNCTION__); \
                         ^~~~~~~~~~~~~~~~~
./macro.h:299:22: note: in expansion of macro 'assert_message_se'
 #define assert(expr) assert_message_se(expr, #expr)
                      ^~~~~~~~~~~~~~~~~
./sigbus.c:88:9: note: in expansion of macro 'assert'
         assert(sn == SIGBUS);
         ^~~~~~
./log.h:177:9: note: function ‘log_assert_failed_realm‘ is not known to be async-signal-safe
         log_assert_failed_realm(LOG_REALM, (text), __VA_ARGS__)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:283:25: note: in expansion of macro 'log_assert_failed'
                         log_assert_failed(message, __FILE__, __LINE__, __PRETTY_FUNCTION__); \
                         ^~~~~~~~~~~~~~~~~
./macro.h:299:22: note: in expansion of macro 'assert_message_se'
 #define assert(expr) assert_message_se(expr, #expr)
                      ^~~~~~~~~~~~~~~~~
./sigbus.c:88:9: note: in expansion of macro 'assert'
         assert(sn == SIGBUS);
         ^~~~~~
In file included from ./sigbus.c:8:
./macro.h:26:24: warning: possible asynchronous-unsafe function ‘__builtin_expect‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                       ~^~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:282:21: note: in expansion of macro '_unlikely_'
                 if (_unlikely_(!(expr)))                                \
                     ^~~~~~~~~~
./macro.h:299:22: note: in expansion of macro 'assert_message_se'
 #define assert(expr) assert_message_se(expr, #expr)
                      ^~~~~~~~~~~~~~~~~
./sigbus.c:89:9: note: in expansion of macro 'assert'
         assert(si);
         ^~~~~~
./macro.h:26:24: note: function ‘__builtin_expect‘ is not known to be async-signal-safe
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                       ~^~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:282:21: note: in expansion of macro '_unlikely_'
                 if (_unlikely_(!(expr)))                                \
                     ^~~~~~~~~~
./macro.h:299:22: note: in expansion of macro 'assert_message_se'
 #define assert(expr) assert_message_se(expr, #expr)
                      ^~~~~~~~~~~~~~~~~
./sigbus.c:89:9: note: in expansion of macro 'assert'
         assert(si);
         ^~~~~~
In file included from ./macro.h:458,
                 from ./sigbus.c:8:
./log.h:177:9: warning: possible asynchronous-unsafe function ‘log_assert_failed_realm‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
         log_assert_failed_realm(LOG_REALM, (text), __VA_ARGS__)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:283:25: note: in expansion of macro 'log_assert_failed'
                         log_assert_failed(message, __FILE__, __LINE__, __PRETTY_FUNCTION__); \
                         ^~~~~~~~~~~~~~~~~
./macro.h:299:22: note: in expansion of macro 'assert_message_se'
 #define assert(expr) assert_message_se(expr, #expr)
                      ^~~~~~~~~~~~~~~~~
./sigbus.c:89:9: note: in expansion of macro 'assert'
         assert(si);
         ^~~~~~
./log.h:177:9: note: function ‘log_assert_failed_realm‘ is not known to be async-signal-safe
         log_assert_failed_realm(LOG_REALM, (text), __VA_ARGS__)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:283:25: note: in expansion of macro 'log_assert_failed'
                         log_assert_failed(message, __FILE__, __LINE__, __PRETTY_FUNCTION__); \
                         ^~~~~~~~~~~~~~~~~
./macro.h:299:22: note: in expansion of macro 'assert_message_se'
 #define assert(expr) assert_message_se(expr, #expr)
                      ^~~~~~~~~~~~~~~~~
./sigbus.c:89:9: note: in expansion of macro 'assert'
         assert(si);
         ^~~~~~
In file included from ./sigbus.c:8:
./macro.h:26:24: warning: possible asynchronous-unsafe function ‘__builtin_expect‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                       ~^~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:282:21: note: in expansion of macro '_unlikely_'
                 if (_unlikely_(!(expr)))                                \
                     ^~~~~~~~~~
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:92:17: note: in expansion of macro 'assert_se'
                 assert_se(sigaction(SIGBUS, &old_sigaction, NULL) == 0);
                 ^~~~~~~~~
./macro.h:26:24: note: function ‘__builtin_expect‘ is not known to be async-signal-safe
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                       ~^~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:282:21: note: in expansion of macro '_unlikely_'
                 if (_unlikely_(!(expr)))                                \
                     ^~~~~~~~~~
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:92:17: note: in expansion of macro 'assert_se'
                 assert_se(sigaction(SIGBUS, &old_sigaction, NULL) == 0);
                 ^~~~~~~~~
In file included from ./macro.h:458,
                 from ./sigbus.c:8:
./log.h:177:9: warning: possible asynchronous-unsafe function ‘log_assert_failed_realm‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
         log_assert_failed_realm(LOG_REALM, (text), __VA_ARGS__)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:283:25: note: in expansion of macro 'log_assert_failed'
                         log_assert_failed(message, __FILE__, __LINE__, __PRETTY_FUNCTION__); \
                         ^~~~~~~~~~~~~~~~~
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:92:17: note: in expansion of macro 'assert_se'
                 assert_se(sigaction(SIGBUS, &old_sigaction, NULL) == 0);
                 ^~~~~~~~~
./log.h:177:9: note: function ‘log_assert_failed_realm‘ is not known to be async-signal-safe
         log_assert_failed_realm(LOG_REALM, (text), __VA_ARGS__)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:283:25: note: in expansion of macro 'log_assert_failed'
                         log_assert_failed(message, __FILE__, __LINE__, __PRETTY_FUNCTION__); \
                         ^~~~~~~~~~~~~~~~~
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:92:17: note: in expansion of macro 'assert_se'
                 assert_se(sigaction(SIGBUS, &old_sigaction, NULL) == 0);
                 ^~~~~~~~~
./sigbus.c:98:19: warning: possible asynchronous-unsafe function ‘page_size‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
         ul = ul / page_size();
                   ^~~~~~~~~~~
./sigbus.c:98:19: note: function ‘page_size‘ is not known to be async-signal-safe
./sigbus.c:99:19: warning: possible asynchronous-unsafe function ‘page_size‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
         ul = ul * page_size();
                   ^~~~~~~~~~~
./sigbus.c:99:19: note: function ‘page_size‘ is not known to be async-signal-safe
./sigbus.c:103:9: warning: possible asynchronous-unsafe function ‘sigbus_push‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
         sigbus_push(aligned);
         ^~~~~~~~~~~~~~~~~~~~
In file included from ./sigbus.c:8:
./macro.h:26:24: note: function ‘sigbus_push‘ calls function ‘__builtin_expect‘
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                       ~^~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:282:21: note: in expansion of macro '_unlikely_'
                 if (_unlikely_(!(expr)))                                \
                     ^~~~~~~~~~
./macro.h:299:22: note: in expansion of macro 'assert_message_se'
 #define assert(expr) assert_message_se(expr, #expr)
                      ^~~~~~~~~~~~~~~~~
./sigbus.c:28:9: note: in expansion of macro 'assert'
         assert(addr);
         ^~~~~~
./macro.h:26:24: note: function ‘__builtin_expect‘ is not known to be async-signal-safe
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                       ~^~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:282:21: note: in expansion of macro '_unlikely_'
                 if (_unlikely_(!(expr)))                                \
                     ^~~~~~~~~~
./macro.h:299:22: note: in expansion of macro 'assert_message_se'
 #define assert(expr) assert_message_se(expr, #expr)
                      ^~~~~~~~~~~~~~~~~
./sigbus.c:28:9: note: in expansion of macro 'assert'
         assert(addr);
         ^~~~~~
In file included from ./macro.h:458,
                 from ./sigbus.c:8:
./log.h:177:9: note: function ‘sigbus_push‘ calls function ‘log_assert_failed_realm‘
         log_assert_failed_realm(LOG_REALM, (text), __VA_ARGS__)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:283:25: note: in expansion of macro 'log_assert_failed'
                         log_assert_failed(message, __FILE__, __LINE__, __PRETTY_FUNCTION__); \
                         ^~~~~~~~~~~~~~~~~
./macro.h:299:22: note: in expansion of macro 'assert_message_se'
 #define assert(expr) assert_message_se(expr, #expr)
                      ^~~~~~~~~~~~~~~~~
./sigbus.c:28:9: note: in expansion of macro 'assert'
         assert(addr);
         ^~~~~~
./log.h:177:9: note: function ‘log_assert_failed_realm‘ is not known to be async-signal-safe
         log_assert_failed_realm(LOG_REALM, (text), __VA_ARGS__)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:283:25: note: in expansion of macro 'log_assert_failed'
                         log_assert_failed(message, __FILE__, __LINE__, __PRETTY_FUNCTION__); \
                         ^~~~~~~~~~~~~~~~~
./macro.h:299:22: note: in expansion of macro 'assert_message_se'
 #define assert(expr) assert_message_se(expr, #expr)
                      ^~~~~~~~~~~~~~~~~
./sigbus.c:28:9: note: in expansion of macro 'assert'
         assert(addr);
         ^~~~~~
./sigbus.c:32:21: note: function ‘sigbus_push‘ calls function ‘__sync_bool_compare_and_swap_8‘
                 if (__sync_bool_compare_and_swap(&sigbus_queue[u], NULL, addr)) {
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./sigbus.c:32:21: note: function ‘__sync_bool_compare_and_swap_8‘ is not known to be async-signal-safe
./sigbus.c:33:25: note: function ‘sigbus_push‘ calls function ‘__sync_fetch_and_add_4‘
                         __sync_fetch_and_add(&n_sigbus_queue, 1);
                         ^~~~~~~~~~~~~~~~~~~~
./sigbus.c:33:25: note: function ‘__sync_fetch_and_add_4‘ is not known to be async-signal-safe
./sigbus.c:42:17: note: function ‘sigbus_push‘ calls function ‘__sync_synchronize‘
                 __sync_synchronize();
                 ^~~~~~~~~~~~~~~~~~~~
./sigbus.c:42:17: note: function ‘__sync_synchronize‘ is not known to be async-signal-safe
./sigbus.c:48:21: note: function ‘sigbus_push‘ calls function ‘__sync_bool_compare_and_swap_4‘
                 if (__sync_bool_compare_and_swap(&n_sigbus_queue, c, c + SIGBUS_QUEUE_MAX))
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./sigbus.c:48:21: note: function ‘__sync_bool_compare_and_swap_4‘ is not known to be async-signal-safe
In file included from ./sigbus.c:8:
./sigbus.c:107:19: warning: possible asynchronous-unsafe function ‘page_size‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
         assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:26:44: note: in definition of macro '_unlikely_'
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                                            ^
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:107:9: note: in expansion of macro 'assert_se'
         assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
         ^~~~~~~~~
./sigbus.c:107:19: note: function ‘page_size‘ is not known to be async-signal-safe
         assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:26:44: note: in definition of macro '_unlikely_'
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                                            ^
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:107:9: note: in expansion of macro 'assert_se'
         assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
         ^~~~~~~~~
./sigbus.c:107:19: warning: possible asynchronous-unsafe function ‘mmap‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
         assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:26:44: note: in definition of macro '_unlikely_'
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                                            ^
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:107:9: note: in expansion of macro 'assert_se'
         assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
         ^~~~~~~~~
./sigbus.c:107:19: note: function ‘mmap‘ is not known to be async-signal-safe
         assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:26:44: note: in definition of macro '_unlikely_'
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                                            ^
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:107:9: note: in expansion of macro 'assert_se'
         assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
         ^~~~~~~~~
./macro.h:26:24: warning: possible asynchronous-unsafe function ‘__builtin_expect‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                       ~^~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:282:21: note: in expansion of macro '_unlikely_'
                 if (_unlikely_(!(expr)))                                \
                     ^~~~~~~~~~
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:107:9: note: in expansion of macro 'assert_se'
         assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
         ^~~~~~~~~
./macro.h:26:24: note: function ‘__builtin_expect‘ is not known to be async-signal-safe
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                       ~^~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:282:21: note: in expansion of macro '_unlikely_'
                 if (_unlikely_(!(expr)))                                \
                     ^~~~~~~~~~
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:107:9: note: in expansion of macro 'assert_se'
         assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
         ^~~~~~~~~
In file included from ./macro.h:458,
                 from ./sigbus.c:8:
./log.h:177:9: warning: possible asynchronous-unsafe function ‘log_assert_failed_realm‘ in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
         log_assert_failed_realm(LOG_REALM, (text), __VA_ARGS__)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:283:25: note: in expansion of macro 'log_assert_failed'
                         log_assert_failed(message, __FILE__, __LINE__, __PRETTY_FUNCTION__); \
                         ^~~~~~~~~~~~~~~~~
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:107:9: note: in expansion of macro 'assert_se'
         assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
         ^~~~~~~~~
./log.h:177:9: note: function ‘log_assert_failed_realm‘ is not known to be async-signal-safe
         log_assert_failed_realm(LOG_REALM, (text), __VA_ARGS__)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:283:25: note: in expansion of macro 'log_assert_failed'
                         log_assert_failed(message, __FILE__, __LINE__, __PRETTY_FUNCTION__); \
                         ^~~~~~~~~~~~~~~~~
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:107:9: note: in expansion of macro 'assert_se'
         assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
         ^~~~~~~~~
In file included from ./sigbus.c:8:
./sigbus.c:92:27: warning: errno may be changed in signal handler ‘sigbus_handler‘ [-fplugin=csigsafe]
                 assert_se(sigaction(SIGBUS, &old_sigaction, NULL) == 0);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./macro.h:26:44: note: in definition of macro '_unlikely_'
 #define _unlikely_(x) (__builtin_expect(!!(x),0))
                                            ^
./macro.h:292:25: note: in expansion of macro 'assert_message_se'
 #define assert_se(expr) assert_message_se(expr, #expr)
                         ^~~~~~~~~~~~~~~~~
./sigbus.c:92:17: note: in expansion of macro 'assert_se'
                 assert_se(sigaction(SIGBUS, &old_sigaction, NULL) == 0);
                 ^~~~~~~~~
